[package]
name = "advent2020"
version = "0.1.0"
authors = ["Gautam Mohan <s.gautam.mohan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
